### PR TITLE
Handle streamed message chunks in playground

### PR DESCRIPTION
**Pull request by dqbd**

### CODE REVIEW

**Review by jacoblee93 — APPROVED** [review]
Looks good, are we worried about bundle size? Wouldn't be hard to do this ad-hoc without `langchain` as a dep

**Comment by dqbd** [comment]
As we're importing only `AIMessageChunk` from `langchain/schema`, I'm not too worried of bundle size increase. Nevertheless, there is some benefit of inlining the core code paths instead, so going with that.

Previous:
CleanShot 2023-10-24 at 15 42 46

Before inline:
CleanShot 2023-10-24 at 15 44 02

After inline:
CleanShot 2023-10-24 at 15 50 39

**Comment by dqbd** [comment]
Note: ideally we would get rid of MUI entirely if we're concerned of the bundle size instead

**Comment by jacoblee93** [comment]
No worries - wouldn't hate that either in the long run as I don't love these tester rank things, but definitely not in scope here

**Pull request merged**
