### PR TITLE
Add a Deploy to Railway Button

### PR DESCRIPTION
**Pull request by PaulLockett**
This adds a one click deploy button for railway that deploys LangServe with the ability to use templates.

### CODE REVIEW

**Comment by PaulLockett** [comment]
More Context on this button: https://x.com/PaulLockettkpb/status/1726869527147970711?s=20

the Repo for the Railway deployment: https://github.com/PaulLockett/LangServe-Railway/tree/main#adding-packages

**Comment by PaulLockett** [comment]
I have filled out the Contributor License Agreement.

**Comment by eyurtsev** [comment]
(@PaulLockett sorry will review in a bit -- need to try this out first)

**Comment by PaulLockett** [comment]
All good. I have been using it in a project for a few clients. Let me know if you run into any issues!

**Comment by PaulLockett** [comment]
> (@PaulLockett sorry for delay will review in a bit -- need to try this out first)

All good. I have been using it in a project for a few clients. Let me know if you run into any issues! @eyurtsev

**Pull request merged**
