### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lucianotonet**
Fix typo

### CODE REVIEW

**Comment by lucianotonet** [comment]
The form file isn't available anymore.
Can someone please check?
@hwchase17

**Comment by eyurtsev** [comment]
@lucianotonet updated the link to the CLA

**Comment by lucianotonet** [comment]
Thanks @eyurtsev 
Done!

**Comment by lucianotonet** [comment]
@eyurtsev cla-bot doesn't seem to be working. Can you verify, please?

**Comment by eyurtsev** [comment]
@lucianotonet You're all set -- the process still has manual steps in it, but I just added you to the list of contributors! Thank you!

**Pull request merged**
