### PR TITLE
docs: AWS deployment (via Copilot CLI) 

### PR DESCRIPTION
**Pull request by JGalego**
This PR adds a one-liner deployment option to AWS via ECS + Fargate using the [Copilot CLI](https://github.com/aws/copilot-cli).

**Advanced**
- `*_API_KEY`'s can be managed securely with [secrets](https://aws.github.io/copilot-cli/docs/developing/secrets/)
- custom resources (like IAM policies granting `bedrock:InvokeModel*` access to specific models) can be easily handled with [addon templates](https://aws.github.io/copilot-cli/docs/developing/addons/workload/#what-does-an-addon-template-look-like)

### CODE REVIEW

**Comment by JGalego** [comment]
CLA link doesn't seem to be working

**Comment by eyurtsev** [comment]
@JGalego updated the cla. Let me know whenever you sign and I can merge the PR! Thanks so much :)

**Comment by JGalego** [comment]
> @JGalego updated the cla. Let me know whenever you sign and I can merge the PR! Thanks so much :)

CLA signed ✍️

**Comment by JGalego** [comment]
For future reference, there's now an AWS Community blog post about LangServe deployments with AWS Copilot 🎉https://community.aws/content/2eY9TZJMipfxYOTafH5AdjPDCKE/deploy-langchain-applications-on-aws-with-langserve

**Pull request merged**
